apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: simple-vpa
  namespace: example02
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind:       Deployment
    name:       simple-deployment
  updatePolicy:
    updateMode: "Auto"
  resourcePolicy:
    containerPolicies:
    - containerName: "webserver-simple"
      minAllowed:
        cpu: "250m"
        memory: "256Mi"
      maxAllowed:
        cpu: "500m"
        memory: "512Mi"
