apiVersion: autoscaling.k8s.io/v1beta1
kind: VerticalPodAutoscaler
metadata:
  name: simple-vpa
  namespace: example02
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind:       Deployment
    name:       simple-deployment
  updatePolicy:
    updateMode: "Auto"