apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: uses-mattermost
  annotations:
    notifications.argoproj.io/subscribe.on-sync-succeeded.mattermost: kk5qf7cukfd7pgynxe9i1jqh5w
spec:
  destination:
    namespace: demo-mattermost
    server: https://kubernetes.default.svc
  project: default
  source:
    path: ./simple-application
    repoURL: https://github.com/codefresh-contrib/gitops-cert-level-2-examples
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
