apiVersion: v1
kind: Service
metadata:
  name: notification-tester-service
spec:
  type: NodePort
  selector:
    app: notification-tester
  ports:
      - nodePort: 31000
        protocol: TCP
        port: 8080
