apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: follow-semver02
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://github.com/codefresh-contrib/gitops-cert-level-2-examples.git
    targetRevision: HEAD
    path: ./image-updater/02-semver-example
   
  destination:
    server: https://kubernetes.default.svc
    namespace: example01

  # Sync policy
  syncPolicy:
    syncOptions:
      - CreateNamespace=true  
   
